FROM node:20-alpine AS base
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm exec prisma generate

RUN pnpm build

EXPOSE 3001
CMD ["node", "dist/index.js"]
