import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-50 text-slate-900 antialiased">
        <header className="border-b border-slate-200 bg-white">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <span className="text-xl font-semibold">Favorite Map App</span>
            <nav className="flex gap-4 text-sm text-slate-600">
              <a href="/" className="hover:text-slate-900">マップ</a>
              <a href="/keywords" className="hover:text-slate-900">キーワード</a>
              <a href="/favorites" className="hover:text-slate-900">お気に入り</a>
            </nav>
          </div>
        </header>

        <main className="mx-auto max-w-5xl px-6 py-10">{children}</main>

        <footer className="border-t border-slate-200 bg-white">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4 text-sm text-slate-500">
            <span>&copy; {new Date().getFullYear()} Favorite Map App</span>
            <span>Powered by Next.js</span>
          </div>
        </footer>
      </body>
    </html>
  );
}
